services:
  server:
    container_name: bus-server
    build: ./bus-server
    command: yarn start
    ports: 
      - 8888:8888
    networks:
      - bus-network

  api:
    container_name: bus-api
    build: ./bus-api
    depends_on:
      - server
    command: yarn start
    ports: 
      - 5000:5000
    networks:
      - bus-network
    env_file:
      - ./bus-api/.env

networks:
  bus-network:
    driver: bridge
